### ISSUE TITLE
Zealot Macro not working with Frozen scythe/extremely slow

### ISSUE THREAD

**Issue by Azazaell** [RoseGoldIsntGay/RGA#1]
Doesnt hit the entity and moves the head extremely slow pls help

**Comment by RoseGoldIsntGay** [comment]
what does "doesnt hit the entity" mean
and head rotation speed can be changed in the config menu

**Comment by Azazaell** [comment]
"doesnt hit the entity" means it doesnt always shoot the mob, most of the time it shoots above the mob or below it. Whats the name of the head rotation speed setting? i cant find it

**Comment by Azazaell** [comment]
found the problem

**Comment by Azazaell** [comment]
when i stop the macro now it sometimes stops jumping and spinning in circles. It stays that way forever

**Comment by RoseGoldIsntGay** [comment]
this project is discontinued
